# Generated by Django 4.0.8 on 2023-10-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_channel_video_url_alter_channel_slug_delete_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
